### PR TITLE
Fix crossChainTransfer for the changes in adapter. fix #137

### LINKED ISSUE #137: Fix crossChainTransfer for the changes in adapter.
The crossChainTransfer function didn’t work in AutomationHub so I had to create a new function `transferMultiasset`. Let’s fix the function for both Turing, signing with Substrate wallet, and Moonriver & Shiden, signing with Ethereum Wallet.

No need to test any other chains for now.

### PR DESCRIPTION
**Pull request by imstar15**
1. Fix address issue in cross-chain transfer
2. Add Moonbeam `crossChainTransferWithEthSigner` function. It is implemented by calling the `xtokens` contract on Moonriver.
3. Add Astar `crossChainTransferWithEthSigner` function. It is implemented by calling the `xcm` contract on Shiden.

### CODE REVIEW

File: packages/config/src/contracts/moonbeam/xtokens.ts [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+  },
+];
+
+const xtokens = {
+  abi,
+  address: "0x0000000000000000000000000000000000000804",
+};
+
+// eslint-disable-next-line import/no-default-export
+export default xtokens;
```
Comment (chrisli30) [inline packages/config/src/contracts/moonbeam/xtokens.ts:104]: If there are multiple exports, we can use `export {abi, address}`. That’s why eslint recommends `import/no-default-export`.

File: packages/config/src/contracts/moonbeam/index.ts [hunk 2]
```diff
@@ -0,0 +1,6 @@
+import xtokens from "./xtokens";
+
+const moonbeam = { xtokens };
+
+// eslint-disable-next-line import/no-default-export
+export default moonbeam;
```
Comment (chrisli30) [inline packages/config/src/contracts/moonbeam/index.ts:6]: `export { moonbeam }`; since we will add more chains to this object later, such as `{acala, moonbeam, astar}`

File: packages/config/src/contracts/index.ts [hunk 3]
```diff
@@ -0,0 +1,7 @@
+import astar from "./astar";
+import moonbeam from "./moonbeam";
+
+const contracts = { astar, moonbeam };
+
+// eslint-disable-next-line import/no-default-export
+export default contracts;
```
Comment (chrisli30) [inline packages/config/src/contracts/index.ts:7]: Try the below lines,

```
import * from `./astar`;
import * from `./moonbeam`;

export {astar, moonbeam};
```

File: packages/adapter/src/utils.ts [hunk 4]
```diff
@@ -175,3 +175,15 @@ export function getDecimalBN(decimals: number | string) {
   const power = new BN(decimals, 10);
   return base.pow(power);
 }
+
+/**
+ * Determine the account type based on the address.
+ * Because 1 byte takes 2 characters in hex string, we can use the length of the address to determine the address type.
+ * AccountKey20: 42 characters with prefix 0x.
```
Comment (chrisli30) [inline packages/adapter/src/utils.ts:182]: Let’s add the 0x check to this function.

const length = _.startWith(address, "0x")? 42: 40;

File: packages/adapter/src/utils.ts [hunk 5]
```diff
@@ -175,3 +175,15 @@ export function getDecimalBN(decimals: number | string) {
...
+ * AccountId32: 66 characters with prefix 0x.
```
Comment (chrisli30) [inline packages/adapter/src/utils.ts:183]: No substrate wallet address contains "0x", so AccountId32 length check should be 64. This function needs to throw an error on all wrong cases instead of using AccountType.AccountId32 as the fall-back.

For example,
```
if starts with 0x
   if length is 42
       AccountType.AccountKey20
else
   if length is 40
       AccountType.AccountKey20
   if length is 64
       AccountType.AccountId32

throw new Error(`Unrecognized address format`);

```

**Review by chrisli30 — CHANGES_REQUESTED** [review]
I have added a few suggestions.

File: packages/config/src/contracts/moonbeam/xtokens.ts (hunk 1 above)
Comment (imstar15) [reply packages/config/src/contracts/moonbeam/xtokens.ts]: Fixed

File: packages/config/src/contracts/moonbeam/index.ts (hunk 2 above)
Comment (imstar15) [reply packages/config/src/contracts/moonbeam/index.ts]: Fixed

File: packages/config/src/contracts/index.ts (hunk 3 above)
Comment (imstar15) [reply packages/config/src/contracts/index.ts]: Fixed

File: packages/adapter/src/utils.ts (hunk 5 above)
Comment (imstar15) [reply packages/adapter/src/utils.ts]: Fixed

File: packages/adapter/src/utils.ts (hunk 4 above)
Comment (imstar15) [reply packages/adapter/src/utils.ts]: Fixed

**Review by chrisli30 — APPROVED** [review]
Okay, the changes look good 👌
